### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by odlg** [NoaHimesaka1873/linux-t2-arch#50]
Hoping for an update soon :-)
6.3.1 is a month old now.

**Comment by Redecorating** [comment]
Sorry about that. I've just merged the autoupdate for 6.3.8-1 so that should be released soon.

I haven't really found myself with much time/motivation (mainly the latter) to work on this so that's the main reason it always takes so long for me to update this. I might look into getting the autoupdater to apply changes to main automatically instead of requiring me to merge it every time

**Comment by Redecorating** [comment]
We've moved this repo to @NoaHimesaka1873 so that it can be maintained alongside the xsanmod kernel so there should be frequent updates now.

**Comment by NoaHimesaka1873** [comment]
Closing since I'm maintainer now and there will be frequent updates.
